services:
  - type: web
    name: ringba-webhook-handler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: GOOGLE_CREDS_JSON
        sync: false
